In [9]:
file_path = r'C:\Users\zhang\Desktop\cif\paper\all_not_charge.xyz'
save_path = r'C:\Users\zhang\Desktop\cif\paper\final.xyz'

In [15]:
# 读取xyz文件并按照给定条件筛选坐标

def read_xyz_file_with_conditions(filename):
    coordinates = []
    with open(filename, 'r') as f:
        lines = f.readlines()
        for line in lines[2:]:  # 从第三行开始读取坐标数据
            parts = line.split()
            count_na = 0
            if len(parts) >= 4:
                atom = parts[0]
                x = float(parts[1])
                y = float(parts[2])
                z = float(parts[3])
                if atom == 'Na':
                    atom = 'Li'
                    count_na +=1
                coordinates.append((atom, x, y, z))
    print(count_na)
    return coordinates

# 使用示例
filename = file_path  # 替换为你的xyz文件名
all_cordinates0 = read_xyz_file_with_conditions(filename)

0


In [11]:
import numpy as np

# 定义盒子的尺寸
box_x = 120
box_y = 120
box_z = 26

# 定义四个圆形区域的参数
circles = [
    (30, 30, 20),
    (30, 90, 20),
    (90, 30, 20),
    (90, 90, 20)
]

def is_inside_circle(x, y, circles):
    for (cx, cy, radius) in circles:
        if (x - cx)**2 + (y - cy)**2 < radius**2:
            return True
    return False

# 生成不重复的800个点
num_points = 1500
points = set()

while len(points) < num_points:
    # 生成一个随机点
    x = np.random.uniform(0, box_x)
    y = np.random.uniform(0, box_y)
    z = np.random.uniform(0, box_z)
    
    # 检查点是否在四个圆形区域之外
    if not is_inside_circle(x, y, circles):
        # 添加到集合中，确保不重复
        points.add((x, y, z))

# 将集合转换为numpy数组
points_array = np.array(list(points))

# 输出生成的点
print(points_array)


[[117.03753611  79.41520372  16.16417643]
 [118.45625891  79.70497182  22.87794119]
 [ 72.34811279 100.2235557   25.38613375]
 ...
 [119.05164125  81.90499775   1.34809518]
 [112.78988258  83.2395087    9.6326176 ]
 [ 66.86468839  42.0599113   14.04206288]]


In [12]:
# 生成随机数，然后融化一下 只要是没有在圆的内部 就可以
new_cordinates = []
si_count = 26
al_count = 27
o_count = 0
li_count = 28

for i in range(si_count):
    points_temp = points_array[0:310]
    x,y,z = points_temp[i,0],points_temp[i,1],points_temp[i,2]
    new_cordinates.append(['Si',x,y,z])
    
for i in range(al_count):
    points_temp = points_array[350:600]
    x,y,z = points_temp[i,0],points_temp[i,1],points_temp[i,2]
    new_cordinates.append(['Al',x,y,z])
    
for i in range(o_count):
    points_temp = points_array[700:750]
    x,y,z = points_temp[i,0],points_temp[i,1],points_temp[i,2]
    new_cordinates.append(['O',x,y,z])
    
    
for i in range(li_count):
    points_temp = points_array[800:1500]
    x,y,z = points_temp[i,0],points_temp[i,1],points_temp[i,2]
    new_cordinates.append(['Li',x,y,z])

In [16]:
final  = all_cordinates0 +  new_cordinates
save_path = r'C:\Users\zhang\Desktop\cif\paper\final.xyz'


In [17]:
# 将坐标写回到xyz文件中
def write_xyz_file(filename, coordinates):
    with open(filename, 'w') as f:
        f.write(f"{len(coordinates)}\n")
        f.write("Atoms\n")
        for atom, x, y, z in coordinates:
            f.write(f"{atom}    {x:.6f}    {y:.6f}    {z:.6f}\n")

# 使用示例
save_path = save_path  # 设置保存文件的路径和文件名
write_xyz_file(save_path, final)
print(f"Filtered coordinates saved to {save_path}")


Filtered coordinates saved to C:\Users\zhang\Desktop\cif\paper\final.xyz
